# Generated by Django 3.0 on 2020-10-06 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category name')),
                ('description', models.TextField(verbose_name='Detailed description')),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Toy name')),
                ('description', models.TextField(verbose_name='Detailed description')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cost of Toy in INR')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand of Toy')),
                ('activity_type', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=20, verbose_name='Activity type')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category', verbose_name='Category of Toy')),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
    ]
