# Generated by Django 3.0 on 2020-10-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('favorite1', models.CharField(max_length=100, verbose_name='Favorite Subject1')),
                ('favorite2', models.CharField(max_length=100, verbose_name='Favorite Subject2')),
                ('favorite3', models.CharField(max_length=100, verbose_name='Favorite Subject3')),
            ],
        ),
    ]
